<definitions name="HelloService"
             targetNamespace="http://www.examples.com/wsdl/HelloService.wsdl"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://www.examples.com/wsdl/HelloService.wsdl"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <message name="SpecialHelloRequest">
        <part name="firstName2" type="xsd:string"/>
    </message>

    <message name="SpecialHelloResponse">
        <part name="greeting2" type="xsd:string"/>
    </message>

    <portType name="Hello_PortType">
        <operation name="specialHello">
            <input message="tns:SpecialHelloRequest"/>
            <output message="tns:SpecialHelloResponse"/>
        </operation>
    </portType>

    <binding name="Hello_Binding" type="tns:Hello_PortType">
        <soap:binding style="rpc"
                      transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="specialHello">
            <soap:operation soapAction="specialHello"/>
            <input>
                <soap:body
                        encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                        namespace="urn:examples:helloservice"
                        use="encoded"/>
            </input>

            <output>
                <soap:body
                        encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                        namespace="urn:examples:helloservice"
                        use="encoded"/>
            </output>
        </operation>
    </binding>

    <service name="Hello_Service">
        <documentation>WSDL File for HelloService</documentation>
        <port binding="tns:Hello_Binding" name="Hello_Port">
            <soap:address
                    location="http://www.examples.com/specialHello/" />
        </port>
    </service>
</definitions>